### ISSUE TITLE
Error with processsamples.py

### ISSUE THREAD

**Issue by lucacozzuto** [UCSC-LoweLab/tRAX#19]
Dear authors, I'm using processsamples.py and I got this error:

```
Rscript /opt/trax//newcoverageplots.R --cov=tRNA/tRNA-coverage.txt --locicov=tRNA/pretRNAs/tRNA-pretRNAcoverage.t
xt --trna=../anno/db-trnatable.txt --samples=samplefile.txt --allcov=tRNA/tRNA-coverage.pdf --runname=tRNA --modo
mics=../anno/db-modomics.txt --combinecov=tRNA/tRNA-combinecoverage.pdf --directory=tRNA
Rscript /opt/trax//boxplotmismatches.R --runname=tRNA --mismatch=tRNA/tRNA-coverage.txt --trna=../anno/db-trnatab
le.txt --samples=samplefile.txt --directory=tRNA/mismatch/
Traceback (most recent call last):
  File "/opt/trax/processsamples.py", line 580, in <module>
    gettraxqc(samplefilename, trnainfo, expinfo, tgirtmode = nofrag)
  File "/opt/trax/processsamples.py", line 262, in gettraxqc
    traxqc.main(samplefile=samplefile,databasename=trnainfo.dbname,experimentname=expinfo.expname,tgirt = tgirtmo
de, output=expinfo.qaoutputname)
  File "/opt/trax/traxqc.py", line 724, in main
    prepresults = checkreadprep(runnames,sampleinfo)
  File "/opt/trax/traxqc.py", line 212, in checkreadprep
    prepdict.update({currsample : prepresults.getmergedpercent(currsample) for currsample in samples}) 
  File "/opt/trax/traxqc.py", line 212, in <dictcomp>
    prepdict.update({currsample : prepresults.getmergedpercent(currsample) for currsample in samples}) 
  File "/opt/trax/traxqc.py", line 130, in getmergedpercent
    return self.merged[sample] / (1.*self.gettotal(sample))
ZeroDivisionError: float division by zero
```

I'm not sure where is the problem, I'm using the hg38 database.

Best,

Luca

**Comment by andrewdholmes** [comment]
OK it looks like that's a problem that can occur with some edge cases in
the data, I'll take a look at it but you should still have access to the
analysis results, the only thing that should be missing is the QC report
summary

**Comment by lucacozzuto** [comment]
Hi! 
I'm wondering if we have any news about this issue. I also got niether volcano nor typescatter plots. 

Thanks!

**Comment by andrewdholmes** [comment]
Alright I've pushed an update to github that should prevent that error
message.  That shouldn't relate to the volcano or typescatter plots though,
are you using a pair file?  If you don't supply a list of pairs then those
files wouldn't be generated
