### ISSUE TITLE
maketrnadb error

### ISSUE THREAD

**Issue by divyanandu** [UCSC-LoweLab/tRAX#6]
Hi, I seem to be getting multiple errors when I run the maketrnadb.py file, specifically in the trnasequtils.py file. This is the command i run

python tRAX/maketrnadb.py --databasename=mm10 --genomefile=mm10_ucsc.fa --trnascanfile=mm10-tRNAs-confidence-set.out --namemapfile=mm10-tRNAs_name_map.txt

and I got the following error:

Traceback (most recent call last):
  File "tRAX/maketrnadb.py", line 7, in <module>
    from trnasequtils import *
  File "/clusterfs/vector/scratch/dnandaku/tRAX/trnasequtils.py", line 207
    print "# STOCKHOLM 1.0"

SyntaxError: Missing parentheses in call to 'print'. Did you mean print("# STOCKHOLM 1.0")?

I went in the file and added the parenthesis. Next when I tried to run it, I got this error:

Traceback (most recent call last):
  File "tRAX/maketrnadb.py", line 7, in <module>
    from trnasequtils import *
  File "/clusterfs/vector/scratch/dnandaku/tRAX/trnasequtils.py", line 209
    print "#=GF ID "+name
                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("#=GF ID "+name)?

When I fixed that as well, I got this error:

Traceback (most recent call last):
  File "tRAX/maketrnadb.py", line 7, in <module>
    from trnasequtils import *
  File "/clusterfs/vector/scratch/dnandaku/tRAX/trnasequtils.py", line 212
    print string.ljust(currname,padlength ) +currseq
               ^
SyntaxError: invalid syntax

Just wondering if there is something I am missing. I am running python 3.7.4 for your reference.

**Comment by divyanandu** [comment]
Looks like the problem is because of the print command difference in python 2 and python 3. I was able to create the file using python 2.7.
