### ISSUE TITLE
Unable to align with bowtie2 - choosemappings.py error

### ISSUE THREAD

**Issue by divyanandu** [UCSC-LoweLab/tRAX#7]
Hi Andrew,

I was able to generate the tRNAdb files, but am facing a problem when trying to run the process samples command. my input command was

`python tRAX/threadprocesssamples.py --experimentname=smallRNAs --databasename=mm10 --samplefile=TestSamples.txt --ensemblgtf=mm10-genes.gtf `

but i get the following error:

```
Mapping Reads
cores: 8
logging to smallRNAs/smallRNAs-mapstats.txt
bowtie2 -x mm10-tRNAgenome -k 100 --very-sensitive --ignore-quals --np 5 --reorder -p 4 -U SRR446506_trimmed.fastq | /clusterfs/vector/scratch/dnandaku/tRAX/choosemappings.py mm10-trnatable.txt --progname=TRAX --fqname=SRR446506_trimmed.fastq --expname=TestSamples.txt | samtools sort -T /tmp/inf_R1temp - -o ./inf_R1.bam
bowtie2 -x mm10-tRNAgenome -k 100 --very-sensitive --ignore-quals --np 5 --reorder -p 4 -U SRR446507_trimmed.fastq | /clusterfs/vector/scratch/dnandaku/tRAX/choosemappings.py mm10-trnatable.txt --progname=TRAX --fqname=SRR446507_trimmed.fastq --expname=TestSamples.txt | samtools sort -T /tmp/inf_R2temp - -o ./inf_R2.bam
bowtie2 -x mm10-tRNAgenome -k 100 --very-sensitive --ignore-quals --np 5 --reorder -p 4 -U SRR446509_trimmed.fastq | /clusterfs/vector/scratch/dnandaku/tRAX/choosemappings.py mm10-trnatable.txt --progname=TRAX --fqname=SRR446509_trimmed.fastq --expname=TestSamples.txt | samtools sort -T /tmp/mock_R1temp - -o ./mock_R1.bam
bowtie2 -x mm10-tRNAgenome -k 100 --very-sensitive --ignore-quals --np 5 --reorder -p 4 -U SRR446508_trimmed.fastq | /clusterfs/vector/scratch/dnandaku/tRAX/choosemappings.py mm10-trnatable.txt --progname=TRAX --fqname=SRR446508_trimmed.fastq --expname=TestSamples.txt | samtools sort -T /tmp/inf_R3temp - -o ./inf_R3.bam
bowtie2 -x mm10-tRNAgenome -k 100 --very-sensitive --ignore-quals --np 5 --reorder -p 4 -U SRR446510_trimmed.fastq | /clusterfs/vector/scratch/dnandaku/tRAX/choosemappings.py mm10-trnatable.txt --progname=TRAX --fqname=SRR446510_trimmed.fastq --expname=TestSamples.txt | samtools sort -T /tmp/mock_R2temp - -o ./mock_R2.bam
Could not map SRR446509_trimmed.fastq, check mapstats file
Exiting...
Traceback (most recent call last):
  File "/clusterfs/vector/scratch/dnandaku/tRAX/choosemappings.py", line 291, in <module>
    getbesttrnamappings(args.trnaname, progname = args.progname, fqname = args.fqname, libname = args.expname, setcountfile = args.trnasetcounts)
  File "/clusterfs/vector/scratch/dnandaku/tRAX/choosemappings.py", line 76, in getbesttrnamappings
    newheader = bamfile.header.to_dict()
AttributeError: 'dict' object has no attribute 'to_dict'
Error outputting data
terminate called after throwing an instance of 'int'
(ERR): bowtie2-align died with signal 6 (ABRT) 

Failure to Bowtie2 map
```
The map-stats file shows:

```
bowtie2 -x mm10-tRNAgenome -k 100 --very-sensitive --ignore-quals --np 5 --reorder -p 4 -U SRR446509_trimmed.fastq | /clusterfs/vector/scratch/dnandaku/tRAX/choosemappings.py mm10-trnatable.txt --progname=TRAX --fqname=SRR446509_trimmed.fastq --expname=TestSamples.txt | samtools sort -T /tmp/mock_R1temp - -o ./mock_R1.bam
Traceback (most recent call last):
  File "/clusterfs/vector/scratch/dnandaku/tRAX/choosemappings.py", line 291, in <module>
    getbesttrnamappings(args.trnaname, progname = args.progname, fqname = args.fqname, libname = args.expname, setcountfile = args.trnasetcounts)
  File "/clusterfs/vector/scratch/dnandaku/tRAX/choosemappings.py", line 76, in getbesttrnamappings
    newheader = bamfile.header.to_dict()
AttributeError: 'dict' object has no attribute 'to_dict'
Error outputting data
terminate called after throwing an instance of 'int'
(ERR): bowtie2-align died with signal 6 (ABRT) 
```
Not sure what I am doing incorrectly here..

**Comment by andrewdholmes** [comment]
That looks like an issue where the pysam version you have is out of date.
Make sure you using the latest version of pysam.
